version: '3.9'
services:
  db:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - custom_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - custom_network
    restart: always
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
      
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    restart: always

networks:
  custom_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  minio_data: