// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetFamily.VolunteerRequests.Infrastructure.DbContexts;

#nullable disable

namespace PetFamily.VolunteerRequests.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetFamily.VolunteerRequests.Domain.AggregateRoot.VolunteerRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DiscussionId")
                        .HasColumnType("uuid")
                        .HasColumnName("discussion_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty<Dictionary<string, object>>("RejectionComment", "PetFamily.VolunteerRequests.Domain.AggregateRoot.VolunteerRequest.RejectionComment#RejectionComment", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("rejection_comment");
                        });

                    b.HasKey("Id")
                        .HasName("pk_volunteer_requests");

                    b.ToTable("volunteer_requests", (string)null);
                });

            modelBuilder.Entity("PetFamily.VolunteerRequests.Domain.AggregateRoot.VolunteerRequest", b =>
                {
                    b.OwnsOne("PetFamily.VolunteerRequests.Domain.ValueObjects.VolunteerInfo", "VolunteerInfo", b1 =>
                        {
                            b1.Property<Guid>("VolunteerRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Requisites")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("requisites");

                            b1.HasKey("VolunteerRequestId");

                            b1.ToTable("volunteer_requests");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerRequestId")
                                .HasConstraintName("fk_volunteer_requests_volunteer_requests_id");

                            b1.OwnsOne("PetFamily.SharedKernel.ValueObjects.Experience", "Experience", b2 =>
                                {
                                    b2.Property<Guid>("VolunteerInfoVolunteerRequestId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("experience");

                                    b2.HasKey("VolunteerInfoVolunteerRequestId");

                                    b2.ToTable("volunteer_requests");

                                    b2.WithOwner()
                                        .HasForeignKey("VolunteerInfoVolunteerRequestId")
                                        .HasConstraintName("fk_volunteer_requests_volunteer_requests_id");
                                });

                            b1.Navigation("Experience")
                                .IsRequired();
                        });

                    b.Navigation("VolunteerInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
